name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1 
        with:
          bun-version: latest  

      - name: Install Dependencies
        run: bun install  

      - name: Run Bun Linter
        run: bun lint
